In [7]:
from theano import tensor as T
import numpy as np
import theano

In [19]:
# fake word embeddings (just for this demonstration)
z1 = np.arange(4).repeat(5).reshape([4,5]).astype(theano.config.floatX)
_z1 = theano.shared(z1, borrow=True)
_z1.get_value()

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.]], dtype=float32)

In [11]:
# real initial state
n_hidd = 10
h0  = np.zeros((1, n_hidd)).astype(theano.config.floatX)
_h0 = theano.shared(h0, borrow=True)
_h0.get_value()

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [25]:
# fake weight matrices
_W_x = np.random.randn(5,n_hidd)
_W_h = np.random.randn(n_hidd, n_hidd)
print(_W_x.shape)
print(_W_h.shape)

(5, 10)
(10, 10)


In [28]:
# our step function
def _step(_x_tm1, _h_tm1, _W_x, W_h):
    return _h_tm1+1


# This creates the variable length computation graph (unrols the rnn)
_h, updates = theano.scan(fn=_step,  
                          sequences=_z1, 
                          outputs_info=dict(initial=_h0),
                          non_sequences=[_W_x ,_W_h])


In [31]:
f = theano.function(inputs=[], outputs=_h, updates=updates)

In [32]:
f()

array([[[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.]],

       [[ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.]],

       [[ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.]]], dtype=float32)